#!/bin/sh

#image references
sed -I -e 's/images\.qa1/images/g' backenddetect.vcl
sed -I -e 's/photos\.qa1/photos/g' backenddetect.vcl
sed -I -e 's/sc\.qa1/sc/g' backenddetect.vcl
sed -I -e 's/sc\.qa1/sc/g' img-recv.vcl
sed -I -e 's/images\.qa1/images/g' img-recv.vcl
sed -I -e 's/photos\.qa1/photos/g' img-recv.vcl

#These files should not contain html so a blank qa1 is ok
sed -I -e 's/\ qa1/\ www/g' *-recv.vcl
sed -I -e 's/\qa1\\/\www\\/g' *-recv.vcl
sed -I -e 's/\qa1\./\www\./g' *-recv.vcl
sed -I -e 's/\qa2/\www/g' *-recv.vcl
sed -I -e 's/\ qa1/\ www/g' *-fetch.vcl
sed -I -e 's/\qa1\./\www\./g' *-fetch.vcl
sed -I -e 's/\qa1\\/\www\\/g' *-fetch.vcl
sed -I -e 's/\qa2/\www/g' *-fetch.vcl
sed -I -e 's/\ qa1/\ www/g' backenddetect.vcl
sed -I -e 's/\qa1\\/\www\\/g' backenddetect.vcl
sed -I -e 's/\qa1\./\www\./g' backenddetect.vcl
sed -I -e 's/\qa2/\www/g' backenddetect.vcl
sed -I -e 's/\groups.www/\groups/g' backenddetect.vcl
sed -I -e 's/\ qa1/\ www/g' redirect.vcl
sed -I -e 's/\qa1\\/\www\\/g' redirect.vcl
sed -I -e 's/\qa1\./\www\./g' redirect.vcl
sed -I -e 's/\qa2/\www/g' redirect.vcl
sed -I -e 's/\ qa1/\ www/g' default.vcl
sed -I -e 's/\qa1\\/\www\\/g' default.vcl
sed -I -e 's/\qa1\./\www\./g' default.vcl
sed -I -e 's/\qa2/\www/g' default.vcl

#pages with synthetic html
sed -I -e 's/qa1\\\./www\\\./g' *-error.vcl
sed -I -e 's/qa1\\\./www\\\./g' *-no*.vcl

#pages with qa1 present
sed -I -e 's/qa1.everyday/www.everyday/g' *-error.vcl
sed -I -e 's/qa1.everyday/www.everyday/g' *-no*.vcl
sed -I -e 's/qa1.whatto/www.whatto/g' *-error.vcl
sed -I -e 's/qa1.daily/www.daily/g' *-error.vcl

